---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: customers-service
  name: customers-service
  namespace: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers-service
  strategy: { }
  template:
    metadata:
      labels:
        app: customers-service
    spec:
      containers:
        - image: ${REPOSITORY_PREFIX}/spring-petclinic-cloud-customers-service-otel:latest
          name: customers-service
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
            initialDelaySeconds: 90
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
            initialDelaySeconds: 15
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 10" ]
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kubernetes
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://customers-db-mysql.spring-petclinic.svc.cluster.local:3306/customers_service_db?queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor&zipkinServiceName=customers-db
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: customers-db-mysql
                  key: mysql-root-password
            - name: SPLUNK_OTEL_AGENT
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: SPLUNK_METRICS_ENDPOINT
              value: http://$(SPLUNK_OTEL_AGENT):9943
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://$(SPLUNK_OTEL_AGENT):4317
            - name: OTEL_SERVICE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels[0]
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: deployment.environment=tj-devlab
          ports:
            - containerPort: 8080
      restartPolicy: Always
status: { }
